create table ROOM
(
    ROOMTYPE NUMBER generated as identity,
    ROOMDESC VARCHAR2(10)
)
/

INSERT INTO PAWAN1478.ROOM (ROOMTYPE, ROOMDESC) VALUES (101, '3NONAC');
INSERT INTO PAWAN1478.ROOM (ROOMTYPE, ROOMDESC) VALUES (102, '3NONAC');
INSERT INTO PAWAN1478.ROOM (ROOMTYPE, ROOMDESC) VALUES (103, '3AC');
INSERT INTO PAWAN1478.ROOM (ROOMTYPE, ROOMDESC) VALUES (104, '3AC');
INSERT INTO PAWAN1478.ROOM (ROOMTYPE, ROOMDESC) VALUES (105, '2AC');
