create table COURSE
(
    COURSEID NUMBER generated as identity,
    TITLE    VARCHAR2(10),
    CREDITS  VARCHAR2(10),
    PREREQ   VARCHAR2(20)
)
/

INSERT INTO PAWAN1478.COURSE (COURSEID, TITLE, CREDITS, PREREQ) VALUES (1001, 'WebDev', 'Pawan', 'HTML');
INSERT INTO PAWAN1478.COURSE (COURSEID, TITLE, CREDITS, PREREQ) VALUES (1002, 'OS', 'Kumar', 'Linux');
INSERT INTO PAWAN1478.COURSE (COURSEID, TITLE, CREDITS, PREREQ) VALUES (1003, 'DBMS', 'Nikhil', 'C');
INSERT INTO PAWAN1478.COURSE (COURSEID, TITLE, CREDITS, PREREQ) VALUES (1004, 'PDC', 'Adhikari', 'MA');
INSERT INTO PAWAN1478.COURSE (COURSEID, TITLE, CREDITS, PREREQ) VALUES (1005, 'B.com', 'Rishab', null);
