create table LOCATION
(
    ROOMID   NUMBER generated as identity,
    BUILDING VARCHAR2(20),
    ROOMNO   NUMBER not null,
    CAPACITY NUMBER not null,
    ROOMTYPE VARCHAR2(10)
)
/

INSERT INTO PAWAN1478.LOCATION (ROOMID, BUILDING, ROOMNO, CAPACITY, ROOMTYPE) VALUES (1001, 'WingA', 601, 3, 'C');
INSERT INTO PAWAN1478.LOCATION (ROOMID, BUILDING, ROOMNO, CAPACITY, ROOMTYPE) VALUES (1002, 'WingA', 602, 3, 'C');
INSERT INTO PAWAN1478.LOCATION (ROOMID, BUILDING, ROOMNO, CAPACITY, ROOMTYPE) VALUES (1003, 'WingB', 603, 2, 'A');
INSERT INTO PAWAN1478.LOCATION (ROOMID, BUILDING, ROOMNO, CAPACITY, ROOMTYPE) VALUES (1004, 'WingB', 604, 3, 'H');
INSERT INTO PAWAN1478.LOCATION (ROOMID, BUILDING, ROOMNO, CAPACITY, ROOMTYPE) VALUES (1005, 'WingA', 605, 2, 'L');
