create table ITEM
(
    ITEMNUM NUMBER not null
)
/

INSERT INTO PAWAN1478.ITEM (ITEMNUM) VALUES (1);
INSERT INTO PAWAN1478.ITEM (ITEMNUM) VALUES (2);
INSERT INTO PAWAN1478.ITEM (ITEMNUM) VALUES (3);
INSERT INTO PAWAN1478.ITEM (ITEMNUM) VALUES (5);
