create table REGISTRATION
(
    STUDENTID NUMBER generated as identity,
    CSID      NUMBER not null,
    MIDTERM   VARCHAR2(20),
    FINAL     VARCHAR2(20),
    REGSTATUS VARCHAR2(20)
)
/

INSERT INTO PAWAN1478.REGISTRATION (STUDENTID, CSID, MIDTERM, FINAL, REGSTATUS) VALUES (1001, 123, 'March', 'August', 'Approved');
INSERT INTO PAWAN1478.REGISTRATION (STUDENTID, CSID, MIDTERM, FINAL, REGSTATUS) VALUES (1002, 124, 'March', 'August', 'Approved');
INSERT INTO PAWAN1478.REGISTRATION (STUDENTID, CSID, MIDTERM, FINAL, REGSTATUS) VALUES (1003, 125, 'March', 'August', 'Approved');
INSERT INTO PAWAN1478.REGISTRATION (STUDENTID, CSID, MIDTERM, FINAL, REGSTATUS) VALUES (1004, 126, 'March', 'August', 'Not aprroved');
INSERT INTO PAWAN1478.REGISTRATION (STUDENTID, CSID, MIDTERM, FINAL, REGSTATUS) VALUES (1005, 127, 'March', 'August', 'Pending');
