create table MAJOR
(
    MAJORID   NUMBER ,
    MAJORDESC VARCHAR2(20)
)
/

INSERT INTO PAWAN1478.MAJOR (MAJORID, MAJORDESC) VALUES (1001, 'WT');
INSERT INTO PAWAN1478.MAJOR (MAJORID, MAJORDESC) VALUES (1002, 'OS');
INSERT INTO PAWAN1478.MAJOR (MAJORID, MAJORDESC) VALUES (1003, 'DBMS');
INSERT INTO PAWAN1478.MAJOR (MAJORID, MAJORDESC) VALUES (1003, 'COA');
INSERT INTO PAWAN1478.MAJOR (MAJORID, MAJORDESC) VALUES (1005, 'PDC');
