create table POSITION
(
    POSITIONID   NUMBER generated as identity,
    POSITIONDESC VARCHAR2(30)
)
/

INSERT INTO PAWAN1478.POSITION ( POSITIONDESC) VALUES ( 'Worker');
INSERT INTO PAWAN1478.POSITION ( POSITIONDESC) VALUES ( 'Staff');
INSERT INTO PAWAN1478.POSITION ( POSITIONDESC) VALUES ( 'Deputy');
INSERT INTO PAWAN1478.POSITION ( POSITIONDESC) VALUES ( 'Dept Head');
INSERT INTO PAWAN1478.POSITION ( POSITIONDESC) VALUES ( 'Manager');
