create table DEPARTMENT
(
    DEPTID    NUMBER generated as identity,
    DEPTNAME  VARCHAR2(10),
    FACULTYID NUMBER
)
/

INSERT INTO PAWAN1478.DEPARTMENT (DEPTID, DEPTNAME, FACULTYID) VALUES (1001, 'Maths', 1);
INSERT INTO PAWAN1478.DEPARTMENT (DEPTID, DEPTNAME, FACULTYID) VALUES (1002, 'Physics', 2);
INSERT INTO PAWAN1478.DEPARTMENT (DEPTID, DEPTNAME, FACULTYID) VALUES (1003, 'Chemistry', 3);
INSERT INTO PAWAN1478.DEPARTMENT (DEPTID, DEPTNAME, FACULTYID) VALUES (1004, 'Biology', 4);
INSERT INTO PAWAN1478.DEPARTMENT (DEPTID, DEPTNAME, FACULTYID) VALUES (1005, 'English', 5);
