create table QUALIFICATION
(
    QUALID   NUMBER ,
    QUALDESC VARCHAR2(30)
)
/

INSERT INTO PAWAN1478.QUALIFICATION (QUALID, QUALDESC) VALUES (2001, 'Graduation');
INSERT INTO PAWAN1478.QUALIFICATION (QUALID, QUALDESC) VALUES (2002, 'PhD');
INSERT INTO PAWAN1478.QUALIFICATION (QUALID, QUALDESC) VALUES (2003, 'Highschool');
INSERT INTO PAWAN1478.QUALIFICATION (QUALID, QUALDESC) VALUES (2004, 'Masters');
INSERT INTO PAWAN1478.QUALIFICATION (QUALID, QUALDESC) VALUES (2005, 'Bachelor');
