create table POSITION
(
    POSITIONID   NUMBER generated as identity,
    POSITIONDESC VARCHAR2(30)
)
/

INSERT INTO PAWAN1478.POSITION (POSITIONID, POSITIONDESC) VALUES (1, 'Worker');
INSERT INTO PAWAN1478.POSITION (POSITIONID, POSITIONDESC) VALUES (2, 'Staff');
INSERT INTO PAWAN1478.POSITION (POSITIONID, POSITIONDESC) VALUES (3, 'Deputy');
INSERT INTO PAWAN1478.POSITION (POSITIONID, POSITIONDESC) VALUES (4, 'Dept Head');
INSERT INTO PAWAN1478.POSITION (POSITIONID, POSITIONDESC) VALUES (5, 'Manager');
