create table ROOMS
(
    ROOMTYPE VARCHAR2(30),
    ROOMDESC VARCHAR2(50)
)
/

INSERT INTO PAWAN1478.ROOMS (ROOMTYPE, ROOMDESC) VALUES ('C', 'Classroom');
INSERT INTO PAWAN1478.ROOMS (ROOMTYPE, ROOMDESC) VALUES ('L', 'Lab');
INSERT INTO PAWAN1478.ROOMS (ROOMTYPE, ROOMDESC) VALUES ('H', 'Lecture Hall');
INSERT INTO PAWAN1478.ROOMS (ROOMTYPE, ROOMDESC) VALUES ('AV', 'AV room');
INSERT INTO PAWAN1478.ROOMS (ROOMTYPE, ROOMDESC) VALUES ('A', 'Auditorium');
