create table employee (employeeid number generated by default as identity,
                               lname varchar(10),fname varchar(10),
                               positionid int, supervisor varchar(20),
                               hiredate date, salary int,
                               commission int, deptid int,
                               quaaid int);
create table position (positionid number generated by default as identity,
                               positiondesc varchar(30));
create table dept (deptid number generated by default as identity,
                               deptname varchar(10),location varchar(10),
                               employeeid int);
create table qualification (qualid number generated by default as identity,
                               qualdesc varchar(30));
create table emplevel (levelno number generated by default as identity,
                               lowsalary int, highsalary int);
create table dependent (employeeid number generated by default as identity,
                    dependentid int, depdob date,relation varchar(20));


