create table registration (studentid number generated by default as identity,
                               csid int, midterm varchar(10),final varchar(10),
                               regstatus varchar(20));